- name: ensure work paths exist
  file:
    path: "{{ item }}"
    state: directory
    owner: jenkins
    group: jenkins
  with_items:
    - "{{ nsl_work_install_dir }}"
    - "{{ nsl_work_install_dir }}/DwCA"
    - "{{ nsl_work_install_dir }}/Processed"
    - "{{ taxxas_work_install_dir }}"
    - "{{ taxxas_work_install_dir }}/DwCA"
    - "{{ taxxas_work_install_dir }}/Processed"
    - "{{ combined_work_install_dir }}"
    - "{{ combined_work_install_dir }}/combined"
    - "{{ tmp_dir }}"
  tags:
    - ag-bie-jenkins-config

- name: create jenkins jobs on server
  template:
    src: "{{ item }}.xml"
    dest: "{{ tmp_dir }}/{{ item }}.xml"
    owner: jenkins
    group: jenkins
  with_items: "{{ jenkins_jobs }}"
  tags:
    - ag-bie-jenkins-config

- name: ensure jenkins is running
  service:
    name: jenkins
    state: restarted

- name: wait for jenkins server to get going
  pause:
    seconds: 30

- name: get jenkins cli on server
  get_url:
    url: "http://localhost:9192/jnlpJars/jenkins-cli.jar"
    dest: "{{ tmp_dir }}/jenkins-cli.jar"
    timeout: 60
  tags:
    - ag-bie-jenkins-config

- name: create job script
  template:
    src: "add-job.sh"
    dest: "{{ tmp_dir }}/add-job.sh"
    owner: jenkins
    group: jenkins
  tags:
    - ag-bie-jenkins-config

- name: make the job script runnable
  file:
    path: "{{ tmp_dir }}/add-job.sh"
    mode: a+x
  tags:
    - ag-bie-jenkins-config

- name: add jenkins jobs to jenkins
  shell: ./add-job.sh "{{ item }}"
  args:
    chdir: "{{ tmp_dir }}"
  with_items: "{{ jenkins_jobs }}"
  tags:
    - ag-bie-jenkins-config

- name: create key area
  file:
    path: "{{ config_install_dir }}/.ssh"
    state: directory
    owner: "jenkins"
    group: "jenkins"
    mode: 0700
  when: ag_bie_local_keys is defined
  tags:
    - ag-bie-jenkins-config

- name: copy organisational keys
  copy:
    src: "{{ ag_bie_local_keys }}/"
    dest: "{{ config_install_dir }}/.ssh"
    owner: "jenkins"
    group: "jenkins"
  when: ag_bie_local_keys is defined
  tags:
    - ag-bie-jenkins-config

- name: set permissions on organisational keys
  file:
    path: "{{ config_install_dir }}/.ssh/{{ ag_bie_user }}.pem"
    mode: 0600
  when: ag_bie_local_keys is defined
  tags:
    - ag-bie-jenkins-config






